#!/bin/bash

echo "🚀 CHUTKI Deployment Helper Script"
echo "=================================="

echo ""
echo "📋 Pre-deployment Checklist:"
echo "1. ✅ MongoDB Atlas cluster created"
echo "2. ✅ Render account created"
echo "3. ✅ Netlify account created"
echo "4. ✅ GitHub repository pushed"
echo ""

echo "🔗 Quick Links:"
echo "MongoDB Atlas: https://cloud.mongodb.com/"
echo "Render: https://render.com/"
echo "Netlify: https://netlify.com/"
echo ""

echo "📝 Environment Variables Needed:"
echo ""
echo "Backend (Render):"
echo "NODE_ENV=production"
echo "PORT=10000"
echo "MONGODB_URI=mongodb+srv://user:pass@cluster.mongodb.net/chutki"
echo "JWT_SECRET=your-secure-secret"
echo "SESSION_SECRET=your-secure-secret"
echo "CLIENT_URL=https://your-frontend.netlify.app"
echo ""
echo "Frontend (Netlify):"
echo "VITE_API_BASE_URL=https://your-backend.onrender.com"
echo "VITE_FRONTEND_URL=https://your-frontend.netlify.app"
echo ""

echo "🎯 Deployment Order:"
echo "1. Setup MongoDB Atlas (database)"
echo "2. Deploy Backend to Render"
echo "3. Deploy Frontend to Netlify"
echo "4. Update cross-references"
echo "5. Test everything!"
echo ""

echo "📖 For detailed steps, see: DEPLOYMENT_STEPS.md"
echo "🔧 For MongoDB setup, see: MONGODB_SETUP.md"
echo ""
echo "📄 Files created:"
echo "   - MONGODB_SETUP.md: MongoDB Atlas setup guide"
echo "   - DEPLOYMENT_STEPS.md: Complete deployment guide"
echo "   - backend/render.yaml: Render configuration"
echo "   - netlify.toml: Netlify configuration"
echo "   - .env.example: Environment variables template"